package com.liuhao.orange.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liuhao.orange.db.bean.WetherSearchBean;

import com.liuhao.orange.db.dao.WetherSearchBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wetherSearchBeanDaoConfig;

    private final WetherSearchBeanDao wetherSearchBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wetherSearchBeanDaoConfig = daoConfigMap.get(WetherSearchBeanDao.class).clone();
        wetherSearchBeanDaoConfig.initIdentityScope(type);

        wetherSearchBeanDao = new WetherSearchBeanDao(wetherSearchBeanDaoConfig, this);

        registerDao(WetherSearchBean.class, wetherSearchBeanDao);
    }
    
    public void clear() {
        wetherSearchBeanDaoConfig.clearIdentityScope();
    }

    public WetherSearchBeanDao getWetherSearchBeanDao() {
        return wetherSearchBeanDao;
    }

}
